### ISSUE TITLE
 the supplementary material

### ISSUE THREAD

**Issue by Sun-god-pineapple** [lodeguns/StaSiS-Net#1]
Hi, Thank you so much for your wonderful contribution!
I haven't found the supplementary material(including pre-trained models, source code and  additional experiments ) you mentioned in the paper. Could you please update it at your convenience?
Thank you for your time!

**Comment by lodeguns** [comment]
Github updated,
please refer to this link:
https://drive.google.com/drive/folders/1_atwJnYU61aGYjrKrhh8s32mgfpzYdhh?usp=sharing

**Comment by Sun-god-pineapple** [comment]
> Github updated, please refer to this link: https://drive.google.com/drive/folders/1_atwJnYU61aGYjrKrhh8s32mgfpzYdhh?usp=sharing

Thank you so much!!!!!!

**Comment by Sun-god-pineapple** [comment]
Thank you so much for your reply!
Wishing you a beautiful day!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Francesco ***@***.***&gt;; 
发送时间: 2022年3月2日(星期三) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lodeguns/StaSiS-Net]  the supplementary material (Issue #1)





 
Hi, thank you for your nice words. I'm sorry for the delay but I'm full of work now,  I will update this repository as soon as possible. In the meantime, I suggest you check my work:
 
https://github.com/lodeguns/Cross-X-AI
 
it is used the same model described in StaSiS-Net even if it is trained in a supervised way on simulated data.
 There, there are all the weights and software to get depth estimation.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lodeguns** [comment]
You are welcome!
Wishing you a beautiful day too!
Francesco
