### ISSUE TITLE
Details to Discuss

### ISSUE THREAD

**Issue by Rashfu** [lodeguns/StaSiS-Net#3]
Hi, lodeguns!
After reading your paper, I have a few questions:
1. In Fig.1 of the paper, **why do the left disparity and right dispariyt cross from d to e**? Since Siamese Network 2 is weight shared, it seems that the two disparities can be fed to either side.
2. **Stereo Matcher module** is not the traditional matching like cost volume, but concatenates the left and right disparity through the full connection and convolution layer to obtain the final left parallax.  Am I understanding correctly?
3. Why does the whole algorithm only use **the first channel of RGB** as input?
4. If I want to compare the output of StaSiS-Net with GT depth, what should I do? I think the output of  StaSiS-Net is similar to the one of monocular depth methods, lacking a certain scale. So should I use the median scale strategy like monocular depth estimation to recover to the true disparity scale, and then use the camera parameters to convert  it to the depth?

Thanks for your time! 😄 🌹

**Comment by lodeguns** [comment]
I haven't followed the project for more than 2 years, but I'll try to answer your questions:

1) In the first Siamese, the channels are inverted, so for example the right arm has as input the left channel 
    and as target the right channel.  Vice versa for the other arm of the Siamese.  In the second siamese the same thing is inverted and with weight sharing. This is because in various works the "late integration" of the features has been proven to work better than the "early" integration.

2) Correct

3) As I remember, the images are provided in grayscale.

4) Yes, in monocular it could be a strategy.

In the output, you can use either the left or the right estimation. 
However, in this system, the images are all stereo rectified, which simplifies the next steps.

**Comment by Rashfu** [comment]
@lodeguns  Thanks for your detailed response!

However, when I repalce the images with MICCAI SCARED dataset(decoded  as jpg image and use opencv to resize to (384,192)), the code doesn't work like that:

![图片1](https://user-images.githubusercontent.com/42403175/199710087-4d197303-f0ae-4f12-9375-f6bab11e1538.png)

Any mistakes in the details?

**Comment by lodeguns** [comment]
as I can remember 
the original images are not resized but patched and depatched according to the input size...

**Comment by lodeguns** [comment]
however it is really strange, did you try with the already trained weights?

**Comment by Rashfu** [comment]
Converting jpg files to png files with opencv will fix the bug. 
![1111](https://user-images.githubusercontent.com/42403175/199720128-4d8f29fb-8e1f-406f-9df9-eb661a458ea5.png)
![22222](https://user-images.githubusercontent.com/42403175/199720130-92f00cb8-1286-4c06-9ca3-67e8785a23c5.png)

But I can't figure out the source of the problem. 

- Why the net could not accept jpg images?  
- Why the final output disparity seems worse than the left disparity and does not match the images in the supplementary materials of the paper?😕
![image](https://user-images.githubusercontent.com/42403175/199720881-0a5e307c-aa6d-4cb1-b1cd-8482d2e5c410.png)

And does `run_stasisnet.py` only provide stereo disparity(`D_s` in paper), left disparity`(D_l` in paper) and right disparity((`D_r` in paper))? If so , how could I get the final dispairy `f(D_s)`?

**Comment by lodeguns** [comment]
The f(D_s) is the fuzzy post-processed disparity, not the final result. You should use the thresholding algorithm provided on the Sugeno repository in order to get the final result. I suggest you read the published works more carefully. Thank you.
